create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  shopee_url text not null,
  price integer not null default 0,
  category varchar(100) not null default 'Geral',
  is_active boolean not null default true,
  shop_name varchar(160),
  rating numeric(3, 2),
  sales integer not null default 0,
  discount integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists products_is_active_idx on public.products (is_active);
create index if not exists products_category_idx on public.products (category);
create index if not exists products_created_at_idx on public.products (created_at);

alter table public.products enable row level security;

drop policy if exists "Produtos ativos são públicos" on public.products;
create policy "Produtos ativos são públicos"
on public.products
for select
to anon, authenticated
using (is_active = true);

-- A service role key bypassa RLS e é usada somente nas rotas server-side do Next.js.
-- Não coloque a service role key no frontend.
